version: "3.4"

services:
  app:
    image: monica
    container_name: ${DOCKER_CONTAINER_NAME_PREFIX}monica
    depends_on:
      - db
    ports:
      - 8090:80
    environment:
      - APP_KEY=
      - DB_HOST=db
      - DB_USERNAME=${MONICA_USER}
      - DB_PASSWORD=${MONICA_PASS}
    volumes:
      - ${DOCKER_PATH_PERSISTENT}/monica/data:/var/www/html/storage
    restart: always

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=${MONICA_USER}
      - MYSQL_PASSWORD=${MONICA_PASS}
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql
