version: "3.8"

services:
  diun:
    image: ghcr.io/crazy-max/diun:4.31
    hostname: diun
    command: serve

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ivan/docker/diun:/data

    environment:
      TZ: ${DOCKER_TZ}
      LOG_LEVEL: ${DIUN_LOG_LEVEL:-info}
      LOG_JSON: "false"

      DIUN_DB_PATH: /data/diun.db

      DIUN_WATCH_WORKERS: ${DIUN_WATCH_WORKERS:-20}
      DIUN_WATCH_SCHEDULE: ${DIUN_WATCH_SCHEDULE:-0 1 * * SUN}
      DIUN_WATCH_JITTER: ${DIUN_WATCH_JITTER:-30s}
      DIUN_WATCH_RUNONSTARTUP: "true"
      DIUN_WATCH_FIRSTCHECKNOTIF: "true"

      DIUN_PROVIDERS_SWARM: "true"
      DIUN_PROVIDERS_SWARM_WATCHBYDEFAULT: "true"
      DIUN_PROVIDERS_DOCKER: "true"

      DIUN_NOTIF_TELEGRAM_TOKEN: ${DIUN_TELEGRAM_TOKEN}
      DIUN_NOTIF_TELEGRAM_CHATIDS: ${DIUN_TELEGRAM_CHATIDS}
      DIUN_NOTIF_TELEGRAM_TEMPLATEBODY: 'Docker tag {{ if .Entry.Image.HubLink }}[{{ .Entry.Image }}]({{ .Entry.Image.HubLink }}){{ else }}{{ .Entry.Image }}{{ end }} which you subscribed to through {{ .Entry.Provider }} provider has been {{ if (eq .Entry.Status "new") }}newly added{{ else }}updated{{ end }} on {{ escapeMarkdown .Meta.Hostname }}.'

      DIUN_NOTIF_WEBHOOK_ENDPOINT: ${DIUN_WEBHOOK_ENDPOINT}
      DIUN_NOTIF_WEBHOOK_METHOD: POST
      DIUN_NOTIF_WEBHOOK_HEADERS_CONTENT-TYPE: application/json

    networks:
      - infra_net

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME}
      restart_policy:
        condition: any
        delay: 10s
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      resources:
        reservations:
          cpus: "${DIUN_RES_CPU:-0.10}"
          memory: ${DIUN_RES_MEM:-128M}
        limits:
          cpus: "${DIUN_LIM_CPU:-0.50}"
          memory: ${DIUN_LIM_MEM:-256M}
      labels:
        - "com.centurylinklabs.watchtower.scope=swarm"

networks:
  infra_net:
    external: true
